In [2]:
import numpy as np

my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_array)

mod_array = [list(i) for i in zip(*my_array)][::-1]
print(mod_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3, 6, 9], [2, 5, 8], [1, 4, 7]]
