In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Data Tensor: \n {x_data} \n")
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Data Tensor: \n {x_data} \n")
print(f"Random Tensor: \n {x_rand} \n")

Data Tensor: 
 tensor([[1, 2],
        [3, 4]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Data Tensor: 
 tensor([[1, 2],
        [3, 4]]) 

Random Tensor: 
 tensor([[0.4532, 0.5156],
        [0.6547, 0.3993]]) 



In [6]:
print(f"Data Tensor: \n {x_data} \n")

Data Tensor: 
 tensor([[1, 2],
        [3, 4]]) 



In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9862, 0.3812, 0.7396],
        [0.6367, 0.4339, 0.3085]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")
else:
    print(f"GPU not available, tensor is stored on CPU: {tensor.device}.")

GPU not available, tensor is stored on CPU: cpu.


In [12]:
tensor = torch.ones(4, 4)
print(f"Tensor Before: \n {tensor} \n")
tensor[:,1] = 0
print(f"Tensor After: \n {tensor} \n")

Tensor Before: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Tensor After: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [14]:
print(f"Tensor Before: \n {tensor} \n")
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)

Tensor Before: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [20]:
tensor = torch.randint(low=0, high=5, size=(4, 4), dtype=torch.long)

print(f"Tensor Before: \n {tensor} \n")

# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

Tensor Before: 
 tensor([[4, 4, 1, 1],
        [4, 3, 0, 2],
        [0, 1, 2, 1],
        [1, 0, 4, 0]]) 

tensor.mul(tensor) 
 tensor([[16, 16,  1,  1],
        [16,  9,  0,  4],
        [ 0,  1,  4,  1],
        [ 1,  0, 16,  0]]) 

tensor * tensor 
 tensor([[16, 16,  1,  1],
        [16,  9,  0,  4],
        [ 0,  1,  4,  1],
        [ 1,  0, 16,  0]])


In [22]:
# Matrix Multiplication
print(f"Tensor: \n {tensor} \n")
print(f"Tensor Transpose: \n {tensor.T} \n")
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

Tensor: 
 tensor([[4, 4, 1, 1],
        [4, 3, 0, 2],
        [0, 1, 2, 1],
        [1, 0, 4, 0]]) 

Tensor Transpose: 
 tensor([[4, 4, 0, 1],
        [4, 3, 1, 0],
        [1, 0, 2, 4],
        [1, 2, 1, 0]]) 

tensor.matmul(tensor.T) 
 tensor([[34, 30,  7,  8],
        [30, 29,  5,  4],
        [ 7,  5,  6,  8],
        [ 8,  4,  8, 17]]) 

tensor @ tensor.T 
 tensor([[34, 30,  7,  8],
        [30, 29,  5,  4],
        [ 7,  5,  6,  8],
        [ 8,  4,  8, 17]])


In [23]:
# in place operations

print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[4, 4, 1, 1],
        [4, 3, 0, 2],
        [0, 1, 2, 1],
        [1, 0, 4, 0]]) 

tensor([[9, 9, 6, 6],
        [9, 8, 5, 7],
        [5, 6, 7, 6],
        [6, 5, 9, 5]])


In [24]:
# tensor to numpy

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [25]:
# inplace change in tensor reflects in numpy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [26]:
# numpy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

print("Original Tensor and Numpy Array: ")
print(f"t: {t}")
print(f"n: {n}")

np.add(n, 1, out=n)

print("Changed Tensor and Numpy Array: ")
print(f"t: {t}")
print(f"n: {n}")

Original Tensor and Numpy Array: 
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]
Changed Tensor and Numpy Array: 
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# AUTOGRAD

Usage in PyTorch

Let’s take a look at a single training step. For this example, we load a pretrained resnet18 model from torchvision. We create a random data tensor to represent a single image with 3 channels, and height & width of 64, and its corresponding label initialized to some random values. Label in pretrained models has shape (1,1000).

In [27]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/ruchir/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100.0%


In [28]:
prediction = model(data) # forward pass

In [29]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [30]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [31]:
optim.step() #gradient descent

In [32]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [33]:
Q = 3*a**3 - b**2

In [34]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [35]:
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
